# Basic Site Settings
locale: "en-US"
title: "HOME"
title_separator: "-"
name: &name "Mak1"
description: &description "Data Scientist, Reservoir Computing & International Accounting."
url: https://Yutiankunkun.github.io
baseurl: ""
repository: "Yutiankunkun/Yutiankunkun.github.io"

# Site Author
author:
  avatar: "IMG_6481.JPG"
  name: "Mak1"
  bio: "Sharing thoughts and ideas in English, Japanese, and Chinese."
  location: "Tokyo, Japan"
  email: "yutiankunkun@gmail.com"
  github: "Yutiankunkun"
  kaggle: "Mak1"
  bluesky: "Mak1"
  weibo: "与田困困"
  zhihu: "与田困困"

# Site Settings
words_per_minute: 160
future: true
read_more: "disabled"

# Markdown Processing
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 1..6

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC
